services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    container_name: cachingPg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: caching-demo
      POSTGRES_USER: nelwhix
      POSTGRES_PASSWORD: Password123$
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
